apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: default_answer
    platform: node
    framework: none
    version: message-default_answer-version
  name: default_answer
  namespace: message
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: default_answer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "3000"
        prometheus.io.path: /metrics
      labels:
        app: default_answer
        platform: node
        framework: none
        version: message-default_answer-version
    spec:
      
      containers:
        - env:
            - name: LOG_LEVEL
              value: debug
            - name: NODE_ENV
              value: production
            - name: HTTP_PORT
              value: "3000"
            - name: GRPC_PORT
              value: "50051"
            - name: TZ
              value: Europe/Zurich
            
            
            
            
            
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: default_answer
                  optional: false
          image: docker.coozzy.ch/message-default_answer:message-default_answer-version
          imagePullPolicy: IfNotPresent
          name: default_answer
          resources:
            requests:
              cpu: 1m
              memory: 80Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
